GET http://localhost:3100/iniciar-bot


###
GET http://localhost:3000/detener-bot



###
GET http://localhost:3100/get-data


###
GET http://localhost:3100/test-telegram



# ###
# GET http://localhost:3100/insert-data


###
GET http://localhost:3100/test-price



###
GET http://localhost:3100/test-remaju